### ISSUE TITLE
feat: deployment(where && how to deploy this application)

### ISSUE THREAD

**Issue by mark-at-pieces** [pieces-app/plugin_neovim#10]

**Comment by Bishoy-at-pieces** [comment]
so basically we going to deploy it on GitHub but we can also add it to a few different websites 
- https://vimawesome.com/
- https://dotfyle.com/neovim/plugins/trending

**Comment by Bishoy-at-pieces** [comment]
we can also add it to the lua package manager not really important 
https://luarocks.org/
