### ISSUE TITLE
Pieces Neovim Plug-in Error : The Pieces Plugin has been updated. To ensure it functions correctly, please restart Neovim.

### ISSUE THREAD

**Issue by imkrishnasarathi** [pieces-app/plugin_neovim#58]
I am encountering a persistent warning message with the Pieces Neovim plugin. Each time I open Neovim, I receive the following message:

`Warning: The Pieces Plugin has been updated. To ensure it functions correctly, please restart Neovim.`

I have tried restarting Neovim multiple times, but the warning persists, and the plugin does not seem to function properly.

**Steps to Reproduce:**

- Install the Pieces Neovim plugin.
- Use NvChad with the "Lazy" package manager.
- Install Pieces for Developers Neovim Plugin by adding the plugin details in `plugins.lua`
- Start Neovim.
- Observe the warning message.

**Expected Behavior:**
The plugin should function correctly without requiring repeated restarts.

**Actual Behavior:**
The warning message continues to appear even after multiple restarts, which shows that the plugin is not functioning as expected.

**Environment:**

Neovim Version: v0.10.1
OS: Windows 11
Plugin Manager: Lazy (NvChad)

**Relevant Configuration Files:**

Here are the relevant parts of my configuration:

**init.lua**
```lua
vim.g.base46_cache = vim.fn.stdpath "data" .. "/nvchad/base46/"
vim.g.mapleader = " "

-- bootstrap lazy and all plugins
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"

if not vim.uv.fs_stat(lazypath) then
  local repo = "https://github.com/folke/lazy.nvim.git"
  vim.fn.system { "git", "clone", "--filter=blob:none", repo, "--branch=stable", lazypath }
end

vim.opt.rtp:prepend(lazypath)

local lazy_config = require "configs.lazy"

-- load plugins
require("lazy").setup({
  {
    "NvChad/NvChad",
    lazy = false,
    branch = "v2.5",
    import = "nvchad.plugins",
  },

  { import = "plugins" },
}, lazy_config)

-- load theme
dofile(vim.g.base46_cache .. "defaults")
dofile(vim.g.base46_cache .. "statusline")

require "options"
require "nvchad.autocmds"

vim.schedule(function()
  require "mappings"
end)
```

**lazy.lua**

```lua
vim.g.base46_cache = vim.fn.stdpath "data" .. "/nvchad/base46/"
vim.g.mapleader = " "

-- bootstrap lazy and all plugins
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"

if not vim.uv.fs_stat(lazypath) then
  local repo = "https://github.com/folke/lazy.nvim.git"
  vim.fn.system { "git", "clone", "--filter=blob:none", repo, "--branch=stable", lazypath }
end

vim.opt.rtp:prepend(lazypath)

local lazy_config = require "configs.lazy"

-- load plugins
require("lazy").setup({
  {
    "NvChad/NvChad",
    lazy = false,
    branch = "v2.5",
    import = "nvchad.plugins",
  },

  { import = "plugins" },
}, lazy_config)

-- load theme
dofile(vim.g.base46_cache .. "defaults")
dofile(vim.g.base46_cache .. "statusline")

require "options"
require "nvchad.autocmds"

vim.schedule(function()
  require "mappings"
end)
```

**plugins.lua**
```lua
return {
  {
    "stevearc/conform.nvim",
    opts = require "configs.conform",
  },

  {
    "neovim/nvim-lspconfig",
    config = function()
      require "configs.lspconfig"
    end,
  },
  {
    'kyazdani42/nvim-web-devicons',
    lazy = false,
  },
  {
    'MunifTanjim/nui.nvim',
    lazy = false,
  },
  {  
    'hrsh7th/nvim-cmp',
    lazy = false,
  },  
  {
    'pieces-app/plugin_neovim',
    lazy = false,
  },
}
```

**Comment by Bishoy-at-pieces** [comment]
Hey thank you for pointing that out,
I would like to know your python version you are using. Seems there was an issue in the `UpdateRemotePlugins` command you can run it manually and check the full error and send it here

**Comment by imkrishnasarathi** [comment]
Hey Bishoy! Thanks for trying to help! I'm using Python 3.12.2, and when I manually run `UpdateRemotePlugins`, I see this - 
```
function remote#host#UpdateRemotePlugins[6]..<SNR>27_RegistrationCommands[13]..remote#host#RegisterPlugin, line 5
Plugin "C:/Users/KRISHNA/AppData/Local/nvim-data/lazy/plugin_neovim/rplugin/python3/pieces_python" is already registered                                    remote/host: generated rplugin manifest: C:\Users\KRISHNA\AppData\Local\nvim-data/rplugin.vim                                                               Press ENTER or type command to continue  
```

**Comment by Bishoy-at-pieces** [comment]
Currently python 3.12 is not supported I will try to take a look at 3.12 today and if there is a way to support it, currently use a python version between 3.8 to 3.11
https://github.com/pieces-app/plugin_neovim/issues/53

**Comment by imkrishnasarathi** [comment]
Hey Bishoy! Just uninstalled Python 3.12 and installed 3.11, but this error is still showing up:
```
function remote#host#UpdateRemotePlugins[6]..<SNR>27_RegistrationCommands[13]..remote#host#RegisterPlugin, line 5
Plugin "C:/Users/KRISHNA/AppData/Local/nvim-data/lazy/plugin_neovim/rplugin/python3/pieces_python" is already registeredremote/host: generated rplugin manifest: C:\Users\KRISHNA\AppData\Local\nvim-data/rplugin.vim                           Press ENTER or type command to continue         
```

**Comment by imkrishnasarathi** [comment]
> Can you run `:lua vim.fn.PiecesStartup()`

This is what I get:
![{5F3EBED8-8AA5-4E8A-877D-B58A9C7D6E95}](https://github.com/user-attachments/assets/cfe53071-2764-4726-bf04-f0bb61d66a62)

**Comment by Bishoy-at-pieces** [comment]
@imkrishnasarathi  can you please share C:\Users\KRISHNA\AppData\Local\nvim-data/rplugin.vim file?

**Comment by imkrishnasarathi** [comment]
```vim
" perl plugins


" node plugins


" ruby plugins 
```

Here's the file, it doesn't have anything

**Comment by Bishoy-at-pieces** [comment]
I will create a release next Monday. It should work after the release

**Comment by Bishoy-at-pieces** [comment]
Hey @imkrishnasarathi,
Can you please update the plugin and let me know how it goes?

**Comment by imkrishnasarathi** [comment]
Hey @Bishoy-at-pieces ! So sorry I'm late to reply, I tried updating, and not sure if it's updating or not, but it doesn't work :(
Should I try re installing the whole system of neovim and its _plugins?_

**Comment by 28arnab** [comment]
i also have the same issue it was working fine with wsl neovim but when i switched to neovide in windows its showing that error

works in wsl 

![image](https://github.com/user-attachments/assets/83e14316-2c8d-41bc-9391-9bd68114bcb5)

**Comment by Bishoy-at-pieces** [comment]
Thank you both of you I will be prioritising that issue next Monday

**Comment by Bishoy-at-pieces** [comment]
Hey @28arnab @imkrishnasarathi 

It will be great to have some time chatting about this since I can't reproduce that issue.
https://calendar.app.google/6WNshFBs44BAcoq6A
Feel free to add a time here.

**Comment by Bishoy-at-pieces** [comment]
Hey @28arnab @imkrishnasarathi,
Really sorry for the delay but let me know how it goes after this update planning on update by tomorrow (1.2.0
)

**Comment by bishoy-at-pieces** [comment]
Can you confirm me that is everything is working fine?

**Comment by imkrishnasarathi** [comment]
> Can you confirm me that is everything is working fine?

Hi Bishoy! Let me check and inform you by today!

**Comment by arturolinares** [comment]
So... what are the instructions for lazy?

**Comment by bishoy-at-pieces** [comment]
The code up should be fine
