### ISSUE TITLE
when selecting the code, some highlighting is gone

### ISSUE THREAD

**Issue by kirollos-at-pieces** [pieces-app/plugin_neovim#96]
Note: Also some elements from the markdown are shown as the ** which is for bold

https://github.com/user-attachments/assets/ce114af2-df4d-4b5d-a726-9ddbdbe70c89

**Comment by bishoy-at-pieces** [comment]
This is not a bug

**Comment by kirollos-at-pieces** [comment]
@bishoy-at-pieces what about viewing some elements like '**' for the bold text
